[COMPILE_CFG]
; onnx model input specs. eg: {"x_tst": ((1, 655), "int32"),...}
; static export with sequence_length=512
input_specs={"x_tst": ((1, 512), "int32"), "x_tst_lengths": ((1,), "int32"),"speakers": ((1,), "int32"), "tones": ((1, 512), "int32"), "lang_ids": ((1, 512), "int32"), "bert": ((1, 1024, 512), "float32"), "ja_bert": ((1, 768, 512), "float32"), "sdp_ratio": ((1,), "float32"), "speed": ((1,), "float32")}
