[COMPILE_CFG]
; onnx model input specs. eg: {"x_tst": ((1, 655), "int32"),...}
input_specs={"x_tst": ((1, 239), "int32"), "x_tst_lengths": ((1,), "int32"),"speakers": ((1,), "int32"), "tones": ((1, 239), "int32"), "lang_ids": ((1, 239), "int32"), "bert": ((1, 1024, 239), "float32"), "ja_bert": ((1, 768, 239), "float32"), "sdp_ratio": ((1,), "float32"), "noise_scale_w": ((1,), "float32"), "speed": ((1,), "float32")}
